import { Suspense } from 'react';

import { Geist, Geist_Mono } from 'next/font/google';

import TokenHandler from '@/components/auth/TokenHandler';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Suspense fallback={null}>
                    <TokenHandler />
                </Suspense>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
